config/routes.rb
Rails.application.routes.draw do
  resources :shows, only: [:index, :show]

end

app/models/show.rb
# == Schema Information
#
# Table name: shows
#
#  id            :integer          not null, primary key
#  tmdb_show_id  :integer          not null
#  name          :string           not null
#  country_id    :integer
#  language_id   :integer
#  status_id     :integer
#  type_id       :integer
#  rating        :decimal(4, 2)
#  start_date    :date
#  end_date      :date
#  summary       :string
#  runtime       :integer
#  popularity    :integer          default("0")
#  in_production :boolean          default("f")
#  homepage      :string
#  created_at    :datetime
#  updated_at    :datetime
#

class Show < ActiveRecord::Base
  belongs_to :country
  belongs_to :language
  belongs_to :status
  belongs_to :type
  belongs_to :network

  has_many :media
  has_one :poster, -> { where(media_type: AppConstants::POSTER) }, class_name: Medium
  has_one :backdrop, -> { where(media_type: AppConstants::BACKDROP) }, class_name: Medium
  has_one :trailer, -> { where(media_type: AppConstants::TRAILER) }, class_name: Medium

  has_many :people_shows
  has_many :people, through: :people_shows
  has_and_belongs_to_many :genres
  has_and_belongs_to_many :networks
  has_and_belongs_to_many :production_companies

  validates :tmdb_show_id, :name, presence: true, uniqueness: true
end

app/controllers/shows_controller.rb
class ShowsController < ApplicationController

  def index
    assign_selection_lists
    @shows = shows_service.get_shows(filter_params: filter_params, options: options)
  end

  private

  def filter_params
    params.permit(:country_id, :network_id, :genre_id, :type_id, :language_id, :status_id)
  end

  def options
    params.permit(:page, :sort_by, :search_query)
  end

  def assign_selection_lists
    @filter_lists = ref_data_service.get_ref_data_lists
  end

end

app/views/shows/_counts.html.erb
<div class="headings"> <%= I18n.t('headings.genres') %> </div>
<% @filter_lists[:genres].each_slice(2) do |sliced_genres| %>
    <div class="row">
      <% sliced_genres.each do |genre| %>
      <div class="col-md-6">
        <%= link_to shows_path(genre_id: genre.id) do %>
            <%= genre.name %><span class="badge pull-right"><%= genre.shows.size %></span> <br>
        <% end %>
      </div>
    <% end %>
    </div>
<% end %>
<hr>

<div class="headings"> <%= I18n.t('headings.countries') %> </div>
<% @filter_lists[:countries].each do |country| %>
    <div class="row">
      <div class="col-md-6">
        <%= link_to shows_path(country_id: country.id) do %>
            <%= country.name %><span class="badge pull-right"><%= country.shows.size %></span> <br>
        <% end %>
      </div>
    </div>
<% end %>
<hr>

<div class="headings"> <%= I18n.t('headings.languages') %> </div>
<% @filter_lists[:languages].each do |language| %>
    <div class="row">
      <div class="col-md-6">
        <%= link_to shows_path(language_id: language.id) do %>
            <%= language.name %><span class="badge pull-right"><%= language.shows.size %></span> <br>
        <% end %>
      </div>
    </div>
<% end %>
<hr>

<div class="headings"> <%= I18n.t('headings.types') %> </div>
<% @filter_lists[:types].each do |type| %>
    <div class="row">
      <div class="col-md-6">
        <%= link_to shows_path(type_id: type.id) do %>
            <%= type.name %><span class="badge pull-right"><%= type.shows.size %></span> <br>
        <% end %>
      </div>
    </div>
<% end %>
<hr>

<div class="headings"> <%= I18n.t('headings.statuses') %> </div>
<% @filter_lists[:statuses].each do |status| %>
    <div class="row">
      <div class="col-md-7">
        <%= link_to shows_path(status_id: status.id) do %>
            <%= status.name %><span class="badge pull-right"><%= status.shows.size %></span> <br>
        <% end %>
      </div>
    </div>
<% end %>
<hr>

<div class="headings"> <%= I18n.t('headings.networks') %> </div>
<% @filter_lists[:networks].each_slice(2) do |sliced_networks| %>
    <div class="row">
      <% sliced_networks.each do |network| %>
          <div class="col-md-6">
            <%= link_to shows_path(network_id: network.id) do %>
                <%= network.name %><span class="badge pull-right"><%= network.shows.size %></span> <br>
            <% end %>
          </div>
      <% end %>
    </div>
<% end %>
<div class="bottom-buffer"></div>

app/views/shows/_filter.html.erb
<%= form_tag(shows_path, method: :get) do %>
    <div class="form-group well top-buffer">

      <div class="headings small-bottom-buffer"> <%= I18n.t('headings.sort_by') %> </div>

      <%= radio_button_tag(:sort_by, AppConstants::MOST_POPULAR, params && params[:sort_by] == AppConstants::MOST_POPULAR) %>
      <%= label_tag I18n.t('labels.most_popular') %><br>

      <%= radio_button_tag(:sort_by, AppConstants::LATEST_SHOWS, params && params[:sort_by] == AppConstants::LATEST_SHOWS) %>
      <%= label_tag I18n.t('labels.most_recent') %><br>

      <%= radio_button_tag(:sort_by, AppConstants::TOP_RATED, params && params[:sort_by] == AppConstants::TOP_RATED) %>
      <%= label_tag I18n.t('labels.highest_rated') %>

    </div>

    <div class="form-group well top-buffer">

      <div class="headings"> <%= I18n.t('headings.filters') %> </div>

      <div class="pull-left "><%= I18n.t('labels.genre') %></div>
      <%= select_tag :genre_id, options_from_collection_for_select(@filter_lists[:genres], 'id', 'name', params[:genre_id]), class: 'form-control', :include_blank => true %>

      <div class="pull-left top-buffer"><%= I18n.t('labels.country') %></div>
      <%= select_tag :country_id, options_from_collection_for_select(@filter_lists[:countries], 'id', 'name', params[:country_id]), class: 'form-control', :include_blank => true %>

      <div class="pull-left top-buffer"><%= I18n.t('labels.language') %></div>
      <%= select_tag :language_id, options_from_collection_for_select(@filter_lists[:languages], 'id', 'name', params[:language_id]), class: 'form-control', :include_blank => true %>

      <div class="pull-left top-buffer"><%= I18n.t('labels.status') %></div>
      <%= select_tag :status_id, options_from_collection_for_select(@filter_lists[:statuses], 'id', 'name', params[:status_id]), class: 'form-control', :include_blank => true %>

      <div class="pull-left top-buffer"><%= I18n.t('labels.type') %></div>
      <%= select_tag :type_id, options_from_collection_for_select(@filter_lists[:types], 'id', 'name', params[:type_id]), class: 'form-control', :include_blank => true %>

      <div class="pull-left top-buffer"><%= I18n.t('labels.network') %></div>
      <%= select_tag :network_id, options_from_collection_for_select(@filter_lists[:networks], 'id', 'name', params[:network_id]), class: 'form-control', :include_blank => true %>
    </div>

    <%= submit_tag I18n.t('buttons.submit'), name: nil, class: 'btn bottom-buffer' %>
<% end %>

app/views/shows/_list_shows_layout.html.erb
<% shows.each_slice(6) do |sliced_shows| %>
    <div class="row bottom-buffer">
      <% sliced_shows.each do |show| %>
          <% image = (('http://image.tmdb.org/t/p/original/'+(show.try(:poster).try(:path)) if show.poster)) || AppConstants::DEFAULT_IMAGE %>
          <div class="col-md-2">
            <div class="poster">
              <div class="rating">
                <%= show.rating %>
              </div>
              <%= link_to(image_tag(image, class: 'image'), show) %>
            </div>
            <%= link_to show.name, show, {class: 'show-title'} %>
          </div>
      <% end %>
    </div>
<% end %>
<%= paginate shows %> <br>
<%= page_entries_info shows %>

app/views/shows/index.html.erb
<!--Index of all the shows-->
<div class="col-md-10 pull-left ">
  <%= render partial: 'list_shows_layout', locals: {shows: @shows} %>
</div>

<!--Filter options for users-->
<div class="col-md-2 pull-right panel panel-default">
  <%= render partial: 'filter' %>
</div>

app/views/shows/show.html.erb
<!-- Page Content -->
<div class="container">

  <!-- Portfolio Item Heading -->
  <div class="row">
    <div class="col-lg-12">
      <h1 class="page-header"><%= @show.name %>
      </h1>
    </div>
  </div>
  <!-- /.row -->

  <!-- Portfolio Item Row -->
  <div class="row">

    <div class="col-md-4">
      <%= image_tag(@show.image_url, size: '300x400') %>
    </div>

    <div class="col-md-8">
      <h3>Project Description</h3>
      <%= (@show.summary).html_safe %>
      <h3>Project Details</h3>
      <ul>
        <li>Lorem Ipsum</li>
        <li>Dolor Sit Amet</li>
        <li>Consectetur</li>
        <li>Adipiscing Elit</li>
      </ul>
    </div>

  </div>
  <!-- /.row -->

  <!-- Related Projects Row -->
  <div class="row">

    <div class="col-lg-12">
      <h3 class="page-header">Related Projects</h3>
    </div>
  </div>
  <div class="row col-md-10">
      <% @similar_shows.each do |show| %>
          <div class="col-md-2">
            <%= link_to(image_tag(show.image_url), show) %>
          </div>
      <% end %>
  </div>
</div>